apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      volumes: 
        - name: aws-credentials
          secret:
            secretName: aws-secret
      containers:
      - name: backend-feed
        image: cisseseydou/udagram-api-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
          - name: aws-credentials
            mountPath: /root/.aws/
      restartPolicy: Always
